version: "3"
services:
  reactjs-conf-cntr:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    environment:
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_NAME=devops
